# Generated by Django 5.1.1 on 2024-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='2288dfb7-913b-45e6-88ce-5e17b6992e0e', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.CharField(default='f880bede-c868-4018-a5f7-a623f26d6556', max_length=64, primary_key=True, serialize=False),
        ),
    ]
