# Generated by Django 5.1.1 on 2024-10-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendelouser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='rendelouser',
            name='name',
        ),
    ]
