# Generated by Django 5.1.1 on 2024-11-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='63e84ebc-a0cb-4fb9-9f2b-7dff23b7a3f8', max_length=64, primary_key=True, serialize=False),
        ),
    ]
