# Generated by Django 5.1.1 on 2025-03-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rendeloweboldal.appointment')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='e4b3f9d6-5e7d-4144-9747-f3a6527d64aa', max_length=64, primary_key=True, serialize=False),
        ),
    ]
