# Generated by Django 5.1.1 on 2024-10-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0002_appointment_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='rendeloweboldal.patient'),
        ),
    ]
