# Generated by Django 5.1.1 on 2024-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0002_alter_rendelouser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='ae8f5f88-33b7-41f3-ac8c-1f97db90a5e4', max_length=64, primary_key=True, serialize=False),
        ),
    ]
