# Generated by Django 5.1.1 on 2025-04-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0002_paymentstatus_alter_rendelouser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendeloweboldal.doctor'),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='9e516a58-825c-4468-af4d-e3f895c276f1', max_length=64, primary_key=True, serialize=False),
        ),
    ]
