# Generated by Django 5.1.1 on 2024-10-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0003_alter_treatment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='performer',
        ),
    ]
