# Generated by Django 5.1.1 on 2024-10-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0004_remove_treatment_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendelouser',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rendeloweboldal.patient'),
        ),
    ]
