# Generated by Django 5.1.1 on 2024-10-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0005_rendelouser_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='f3dfc8b1-3410-4921-8d73-c6dbaff1c0e0', max_length=64, primary_key=True, serialize=False),
        ),
    ]
