# Generated by Django 5.1.3 on 2024-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0005_alter_appointment_end_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='5fb1bc19-a933-4e91-92fe-882d4f5a4c7a', max_length=64, primary_key=True, serialize=False),
        ),
    ]
