# Generated by Django 5.1.1 on 2024-10-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0006_alter_rendelouser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(default='445ac1a6-2b69-4206-b2ac-be470649b051', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='a74275f4-8767-4dc6-b687-3d9e60f203a4', max_length=64, primary_key=True, serialize=False),
        ),
    ]
