# Generated by Django 5.1.3 on 2024-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0006_treatment_name_alter_rendelouser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='86102735-83f7-4606-8624-e642bd1a7874', max_length=64, primary_key=True, serialize=False),
        ),
    ]
