# Generated by Django 5.1.1 on 2024-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0007_alter_appointment_id_alter_rendelouser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendelouser',
            name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(default='58eb0673-6aa4-4e04-8f65-1586d7ef2147', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='1dc5e49e-e2d4-4d42-8431-5977552e1956', max_length=64, primary_key=True, serialize=False),
        ),
    ]
