# Generated by Django 5.1.1 on 2024-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0008_remove_rendelouser_patient_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(default='17968d85-0733-4a34-90b1-45f7b7284704', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='79ea1db0-3152-4e60-b601-ea818e65c738', max_length=64, primary_key=True, serialize=False),
        ),
    ]
