# Generated by Django 5.1.1 on 2024-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0009_remove_treatment_patient_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendelouser',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(default='3a531c86-088a-4bb8-aeda-2c78c8b755bc', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='ff6e29ce-919e-405e-a1c3-bf2cefb6d9e5', max_length=64, primary_key=True, serialize=False),
        ),
    ]
