# Generated by Django 5.1.1 on 2024-11-12 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendeloweboldal', '0010_remove_rendelouser_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendelouser',
            name='id',
            field=models.CharField(default='9954e6b3-482e-478c-a07f-fa7f4faa6c7f', max_length=64, primary_key=True, serialize=False),
        ),
    ]
